---
title: "Analyses for Ch1 of Big Report"
author: "DMC"
date: "2023-09-18"
---

Here is the final script to the analyses for Chapter 1.

```{r import FRP data}
rm(list = ls())
load(here::here("imports", "QCd_Data_FRP.RData"))

# create a new list of qc'd data frames to be filtered by year
list_all <- list_all_qc

for(i in 1:length(list_all_qc)){
  #list_2022 <- list() # temporary list
  for(j in 1:length(list_all_qc[[i]])){
    
    rtd_sondeID <- strsplit(names(list_all_qc[[i]])[j], split = " ", fixed = TRUE)[[1]][1] # variable for sondeID
    rtd_dateDeploy <- as.numeric(substr(strsplit(names(list_all_qc[[i]])[j], split = " ", fixed = TRUE)[[1]][2],0,4)) # variable for Deployment date
    rtd_dateRecov <- as.numeric(substr(strsplit(names(list_all_qc[[i]])[j], split = " ", fixed = TRUE)[[1]][3],0,4)) # variable for Recovery date                              0)
    if((rtd_dateDeploy >= 2023 & rtd_dateRecov >= 2023)){
      list_all[[i]][[j]] <- list(NULL)
    } else {
      skip_to_next <- FALSE
      tryCatch({
      list_all[[i]][[j]] <- list_all_qc[[i]][[j]][,c("Site","dts","TempC","SPC","DOmgL","Turb","TempC_qcE","SPC_qcE","DOmgL_qcE","Turb_qcE","Depthm")]
      },
      error = function(e){ skip_to_next <<- TRUE})
      if(skip_to_next) {next}
    }
    rm(rtd_sondeID, rtd_dateDeploy, rtd_dateRecov)
  # when an error is encountered, the loop will be forced to continue and the warning(s) will be shown at the end
  }
}



FLYW <- do.call(rbind.data.frame, list_all[[1]])
FLYW$dts2 <- lubridate::floor_date(FLYW$dts, "15 minutes")
DECK_pool <- do.call(rbind.data.frame, list_all[[2]])
DECK_pool$dts2 <- lubridate::floor_date(DECK_pool$dts, "15 minutes")
DECK_breach <- do.call(rbind.data.frame, list_all[[3]])
DECK_breach$dts2 <- lubridate::floor_date(DECK_breach$dts, "15 minutes")

save(DECK_breach, DECK_pool, FLYW, file = here::here("working","ImportedRaw.RData"))
```


```{r get 1 file for FRP DECK}
library(ggplot2)

rm(list = ls())

load(here::here("working","ImportedRaw.RData"))
'%ni%' = Negate('%in%')

# DECK_breach$Depthm_BR <- DECK_breach$Depthm
# DECK_breach$TempC_BR <- DECK_breach$TempC
# DECK_depthdiff <- merge(DECK_pool, DECK_breach[,c("dts2","TempC_BR","Depthm_BR")], by = "dts2")
# DECK_depthdiff$diff_Depth <- as.numeric(DECK_depthdiff$Depthm) - as.numeric(DECK_depthdiff$Depthm_BR)
# DECK_depthdiff$diff_Temp <- as.numeric(DECK_depthdiff$TempC) - as.numeric(DECK_depthdiff$TempC_BR)
# plo_depth <- ggplot(DECK_depthdiff[which(DECK_depthdiff$diff_Depth < 10 & DECK_depthdiff$diff_Temp > -20),], aes(x = dts2, y = diff_Depth)) +
#   #geom_point()#+
#   geom_point(data = DECK_depthdiff[which(DECK_depthdiff$diff_Depth < 10 & DECK_depthdiff$diff_Temp > -20),], aes(x = dts2, y = diff_Temp), color = "red")

DECK_breach.2 <- DECK_breach[which(DECK_breach$dts2 %ni% DECK_pool$dts2),]
DECK_pool$TempC <- as.numeric(DECK_pool$TempC)
DECK_breach.2$TempC <- as.numeric(DECK_breach.2$TempC)

plo <- ggplot(DECK_pool, aes(x = dts2, y = TempC)) +
  geom_point(color = "black", alpha = 0.2) +
  geom_point(data = DECK_breach.2, aes(x = dts2, y = TempC), color = "red", alpha = 0.2)

#DECK <- rbind.data.frame(DECK_pool, DECK_breach.2)
DECK <- DECK_pool

load(here::here("working","USGS_DeckerTogether.Rds"))
load(here::here("working","USGS_ToeDrain.RData"))

TOED <- df_ToeDrain
TOED$dts2 <- TOED$dateTime
TOED$Depthm <- 1
SACR <- USGS_DECK.2
SACR$dts2 <- SACR$dateTime
SACR$Depthm <- 1

list_all <- list(FLYW, DECK, TOED, SACR)
names(list_all) <- c("FLYW", "DECK", "TOED", "SACR")

save(list_all, file = here::here("working","All_Raw.RData"))
save(DECK, FLYW, file = here::here("working","FRP_Raw.RData"))
```


```{r}
library(ggplot2)
rm(list = ls())
load(here::here("working","All_Raw.RData"))

xSite <- names(list_all)
cols.num <- c("TempC","DOmgL","SPC","Turb")
list_all_4qc <- list()
for(i in 1:length(xSite)){
  df <- list_all[[xSite[i]]]
  df$Site2 <- names(list_all)[i]
  df[cols.num] <- sapply(df[cols.num], as.numeric)
  rownames(df) <- NULL
  dfDUP <- df[duplicated(df$dts2),]
  if(nrow(dfDUP) >0){
    df.2 <- df[-which(duplicated(df$dts2)),]
    if(xSite[i] == "DECK"){
      df.3 <- df.2[-which(is.na(df.2$dts2)==T | df.2$TempC <0.9),]
    } else {
      df.3 <- df.2
    }
  } else {
    df.3 <- df
  }
  list_all_4qc[[i]] <- df.3
}
names(list_all_4qc) <- xSite

save(list_all_4qc, file = here::here("working","All_4qc.RData"))




###################################################
FLYW$TempC <- as.numeric(FLYW$TempC)

dupFLYW <- FLYW[duplicated(FLYW$dts2),]
dupDECK <- DECK[duplicated(DECK$dts2),]

FLYW.2 <- FLYW[-duplicated(FLYW$dts2),]
DECK.2 <- DECK[-duplicated(DECK$dts2),]

FLYW.3 <- FLYW.2[-which(is.na(FLYW.2$dts2)==T),]
DECK.3 <- DECK.2[-which(is.na(DECK.2$dts2)==T | DECK.2$TempC < 0.9),]

DECK.3$Temp_Resto <- DECK.3$TempC

USGS_DECK.2$Temp_Ref <- USGS_DECK.2$tempC
USGS_DECK.2$dts2 <- USGS_DECK.2$dateTime

DECK_all <- merge(DECK.3[,c("dts2","Temp_Resto")], USGS_DECK.2[,c("dts2","Temp_Ref")])
DECK_all$diffTemp <- DECK_all$Temp_Resto - DECK_all$Temp_Ref

plo <- ggplot(DECK_all, aes(x = dts2, y = diffTemp)) +
  geom_point()

load(here::here("working","USGS_ToeDrain.RData"))
df_ToeDrain$Temp_Ref <- df_ToeDrain$tempC
df_ToeDrain$dts2 <- df_ToeDrain$dateTime

FLYW.3$Temp_Resto <- as.numeric(FLYW.3$TempC)

FLYW_all <- merge(FLYW.3[,c("dts2","Temp_Resto")], df_ToeDrain[,c("dts2","Temp_Ref")])
FLYW_all$diffTemp <- FLYW_all$Temp_Resto - FLYW_all$Temp_Ref

plo <- ggplot(FLYW_all, aes(x = dts2, y = diffTemp)) +
  geom_point()
```
Send to WaterVar_QC.Rmd


```{r}

rm(list = ls())
load(here::here("working","QCd2_Data.RData"))

list_DECK <- list_all_QC7$DECK
df_DECK <- rbind.data.frame(data.frame(dateTime = list_DECK$TempC$Datetime,
                                        variable = "TempC",
                                        value = list_DECK$TempC$Var,
                                        Station = "DECK"),
                             data.frame(dateTime = list_DECK$DOmgL$Datetime,
                                        variable = "do",
                                        value = list_DECK$DOmgL$Var,
                                        Station = "DECK"),
                             data.frame(dateTime = list_DECK$SPC$Datetime,
                                        variable = "sc",
                                        value = list_DECK$SPC$Var,
                                        Station = "DECK"),
                             data.frame(dateTime = list_DECK$Turb$Datetime,
                                        variable = "turb",
                                        value = list_DECK$Turb$Var,
                                        Station = "DECK"),
                             data.frame(dateTime = list_DECK$Depthm$Datetime,
                                        variable = "depth",
                                        value = list_DECK$Depthm$Var,
                                        Station = "DECK")
)

list_SACR <- list_all_QC7$SACR
df_SACR <- rbind.data.frame(data.frame(dateTime = list_SACR$TempC$Datetime,
                                        variable = "TempC",
                                        value = list_SACR$TempC$Var,
                                        Station = "SACR"),
                             data.frame(dateTime = list_SACR$DOmgL$Datetime,
                                        variable = "do",
                                        value = list_SACR$DOmgL$Var,
                                        Station = "SACR"),
                             data.frame(dateTime = list_SACR$SPC$Datetime,
                                        variable = "sc",
                                        value = list_SACR$SPC$Var,
                                        Station = "SACR"),
                             data.frame(dateTime = list_SACR$Turb$Datetime,
                                        variable = "turb",
                                        value = list_SACR$Turb$Var,
                                        Station = "SACR"))

list_FLYW <- list_all_QC7$FLYW
df_FLYW <- rbind.data.frame(data.frame(dateTime = list_FLYW$TempC$Datetime,
                                        variable = "TempC",
                                        value = list_FLYW$TempC$Var,
                                        Station = "FLYW"),
                             data.frame(dateTime = list_FLYW$DOmgL$Datetime,
                                        variable = "do",
                                        value = list_FLYW$DOmgL$Var,
                                        Station = "FLYW"),
                             data.frame(dateTime = list_FLYW$SPC$Datetime,
                                        variable = "sc",
                                        value = list_FLYW$SPC$Var,
                                        Station = "FLYW"),
                             data.frame(dateTime = list_FLYW$Turb$Datetime,
                                        variable = "turb",
                                        value = list_FLYW$Turb$Var,
                                        Station = "FLYW")
)

list_TOED <- list_all_QC7$TOED
df_TOED <- rbind.data.frame(data.frame(dateTime = list_TOED$TempC$Datetime,
                                        variable = "TempC",
                                        value = list_TOED$TempC$Var,
                                        Station = "TOED"),
                             data.frame(dateTime = list_TOED$DOmgL$Datetime,
                                        variable = "do",
                                        value = list_TOED$DOmgL$Var,
                                        Station = "TOED"),
                             data.frame(dateTime = list_TOED$SPC$Datetime,
                                        variable = "sc",
                                        value = list_TOED$SPC$Var,
                                        Station = "TOED"),
                             data.frame(dateTime = list_TOED$Turb$Datetime,
                                        variable = "turb",
                                        value = list_TOED$Turb$Var,
                                        Station = "TOED"))

df_DECK.2 <- reshape2::dcast(df_DECK, Station + dateTime ~ variable, value.var = "value")
df_SACR.2 <- reshape2::dcast(df_SACR, Station + dateTime ~ variable, value.var = "value")
df_FLYW.2 <- reshape2::dcast(df_FLYW, Station + dateTime ~ variable, value.var = "value")
df_TOED.2 <- reshape2::dcast(df_TOED, Station + dateTime ~ variable, value.var = "value")

df_DECK.m <- merge(df_DECK.2, df_SACR.2, by = "dateTime", all.x = TRUE, suffixes = c(".RESTO",".ADJ"))
df_FLYW.m <- merge(df_FLYW.2, df_TOED.2, by = "dateTime", all.x = TRUE, suffixes = c(".RESTO",".ADJ"))


df_DECK.m$diff_TempC <- as.numeric(df_DECK.m$TempC.RESTO) - as.numeric(df_DECK.m$TempC.ADJ)
df_FLYW.m$diff_TempC <- as.numeric(df_FLYW.m$TempC.RESTO) - as.numeric(df_FLYW.m$TempC.ADJ)

save(df_DECK.m, df_FLYW.m, file = here::here("working","Merged_4Tide.RData"))
```

Get tide position from depth for all locations
```{r}
library(dplyr)
#library(plyr)
#library(VulnToolkit)
#library(zoo)
#library(data.table)

rm(list = ls())

load(here::here("working","Merged_4Tide.RData"))
'%ni%' <- Negate('%in%')


df_DECK.m$dts2 <- df_DECK.m$dateTime
df_DECK.m <- df_DECK.m[order(df_DECK.m$dts2),]
df_DECK.m <- df_DECK.m[which(is.na(df_DECK.m$depth)==F),]

list_All <- list(df_DECK.m)

detach("package:dplyr", unload=TRUE)
library(plyr)
library(zoo)
library(data.table)

list_All.2 <- list()
for(i in 1:length(list_All)){
  workingDF.1 <- data.frame(list_All[[i]])
  workingDF.1$deltaTime <- as.numeric(workingDF.1$dts2 - data.table::shift(workingDF.1$dts2, fill = data.table::first(workingDF.1$dts2)))/60
  workingDF.1$deltaTime[1] <- 15
  workingDF.1$is15 <- ifelse(workingDF.1$deltaTime == 15, "Y","N")
  List_Split <- split(workingDF.1, cumsum(c(TRUE, diff(workingDF.1$deltaTime > 360) != 0)))
  List_Tides <- list()
  for(j in 1:length(List_Split)){
    workingDF.2 <- List_Split[j][[1]]
    rownames(workingDF.2) <- NULL
    workingDF.2$joinBy <- rownames(workingDF.2)
    if(nrow(workingDF.2) > 20){
      x <- c(rep(-99999,13),workingDF.2$depth,rep(99999,13)) #workingDF.2$depth # this line pads the input vector so that the function returns a more complete output vector
      xz <- as.zoo(x)
      dMax <- rollapply(xz, 26, function(x) which.max(x)==10)
      dMin <- rollapply(xz, 26, function(x) which.min(x)==10)
      dd <- data.frame(dMax,dMin)
      dd$joinBy <- as.numeric(rownames(dd))-16 # this lines up the TRUE/FALSE with the appropriate key
      dd.2 <- merge(workingDF.2, dd, by = "joinBy", all.x = TRUE)
      dd.2$tide <- ifelse(dd.2$dMax == TRUE, "H",NA)
      dd.2$tide <- ifelse(dd.2$dMin == TRUE, "L", dd.2$tide)
      if(is.data.frame(dd)==TRUE){
        List_Tides[[j]] <- dd.2
      }
    } else{
      List_Tides[[j]] <- data.frame()
      }
    workingDF.2 <- NULL
    dd.2 <- NULL
  }
  df_Tides <- do.call(rbind.data.frame, List_Tides)
  #colnames(df_Tides)[2] <- "dts2"
  df_Tides$Station <- unique(workingDF.1$Station)
  list_All.2[[i]] <- df_Tides
  df_Tides <- NULL
  workingDF.1 <- NULL
}

list_All.3 <- list()
for(i in 1:length(list_All.2)){
  workingDF.1 <- data.frame(list_All[[i]])
  workingDF.1$justDate <- as.Date(workingDF.1$dts2)
  focusDate <- unique(workingDF.1$justDate)
  workingDF.1$dts3 <- lubridate::floor_date(workingDF.1$dts2, "15 minutes")
  dts3 <- seq(lubridate::ymd_hms(workingDF.1$dts3[2],tz = "UTC"),lubridate::ymd_hms(workingDF.1$dts3[length(workingDF.1$dts3)],tz = "UTC"), by = '15 mins')
  df_Tides <- list_All.2[[i]]
  #df_Tides$tide[which(df_Tides$level < 0.2)]
  df_Tides$dts3 <- lubridate::floor_date(df_Tides$dts2, "15 minutes")
  df_Tides.Long <- data.frame(dts3)
  df_Tides.Long$justDate <- as.Date(df_Tides.Long$dts3)
  df_Tides.Long <- df_Tides.Long[which(df_Tides.Long$justDate %in% focusDate),]
  df_Tides.Long.2 <- merge(df_Tides.Long, df_Tides[,c("dts3","tide")], by = c("dts3"), all.x = TRUE)
  df_Tides.Long.3 <- merge(df_Tides.Long.2, workingDF.1[,c("dts2","dts3","depth")], by = c("dts3"), all.x = TRUE)
  df_Tides.Long.3$tide_position <- ifelse(df_Tides.Long.3$tide == "H",0,NA)
  df_Tides.Long.3$tide_position[which(df_Tides.Long.3$tide == "L")] <- 1
  df_Tides.Long.3$isValue <- is.na(df_Tides.Long.3$tide_position)
  df_Tides.Long.3$incrementsLength <- rowid(rleid(df_Tides.Long.3$isValue))*df_Tides.Long.3$isValue
  df_Tides.Long.3$tide_position2 <- df_Tides.Long.3$tide_position
  df_Tides.Long.3$tide[which(is.na(df_Tides.Long.3$tide)==TRUE)] <- "None"
  for(j in 1:nrow(df_Tides.Long.3)){
    if(df_Tides.Long.3$tide[j] == "H"){
      if(df_Tides.Long.3$incrementsLength[j-1] <= 100 & df_Tides.Long.3$incrementsLength[j-1] >= 10){
        df_Tides.Long.3$tide_position2[(j- df_Tides.Long.3$incrementsLength[j-1]):(j - 1)] <-
          seq(-1,0, length.out = df_Tides.Long.3$incrementsLength[j-1]+2)[2:((df_Tides.Long.3$incrementsLength[j-1])+1)]
        }
      #df_Tides.Long.3$tide_position2[(j- df_Tides.Long.3$incrementsLength[j-1]):(j - 1)] <- 
      #  try(seq(-1,0, length.out = df_Tides.Long.3$incrementsLength[j-1]+2)[2:((df_Tides.Long.3$incrementsLength[j-1])+1)])
      #}
    }
    if(df_Tides.Long.3$tide[j] == "L"){
      if(df_Tides.Long.3$incrementsLength[j-1] <= 100 & df_Tides.Long.3$incrementsLength[j-1] >= 10){
        df_Tides.Long.3$tide_position2[(j- df_Tides.Long.3$incrementsLength[j-1]):(j - 1)] <- 
          seq(0,1, length.out = df_Tides.Long.3$incrementsLength[j-1]+2)[2:((df_Tides.Long.3$incrementsLength[j-1])+1)]
        }
      #df_Tides.Long.3$tide_position2[(j- df_Tides.Long.3$incrementsLength[j-1]):(j - 1)] <- 
      #  try(seq(0,1, length.out = df_Tides.Long.3$incrementsLength[j-1]+2)[2:((df_Tides.Long.3$incrementsLength[j-1])+1)])
      #}
    }
    }
  list_All.3[[i]] <- df_Tides.Long.3 # After loop has been run, need to execute this one line to add Flyway to list_All.3
}

list_All.4 <- list()
for(i in 1:length(list_All)){
  workingDF.1 <- list_All[[i]]
  workingDF.2 <- list_All.3[[i]]
  workingDF.3 <- merge(workingDF.1, workingDF.2[,c("dts2","tide","tide_position2")], by = c("dts2"), all.x = TRUE)
  list_All.4[[i]] <- workingDF.3
}

plo_test <- ggplot(list_All.4[[1]][which(is.na(list_All.4[[1]]$tide_position2)==TRUE),], aes(dts2, depth)) + geom_point()




depth_final.2 <- do.call(rbind.data.frame, list_All.4)
rm(df_Tides,df_Tides.Long,df_Tides.Long.2,list_All,list_All.2,list_All.3,list_All.4, workingDF.1,workingDF.2,workingDF.3)

save(depth_final.2, file = here::here("working", "Tides_4GAM.RData"))
```

For Temperature (quarter-hourly) - now with tide position from preceding chunk
```{r}
library(plyr)
library(ggplot2)
library(scales)
library(gridExtra)
library(metR)
library(ggpubr)
library(RColorBrewer)
library(mgcv)

rm(list = ls())
load(here::here("working", "Tides_4GAM.RData"))
#load("AllLTM4Analysis_TidePosition_230214.RData")
'%ni%' <- Negate('%in%')

dfwideAll.Final <- depth_final.2

dfwideAll.Final$date2 <- lubridate::date(dfwideAll.Final$dts2)
dfwideAll.Final$year2 <- lubridate::year(dfwideAll.Final$dts2)
dfwideAll.Final$DoY <- lubridate::yday(dfwideAll.Final$dts2)
dfwideAll.Final$hr <- lubridate::hour(dfwideAll.Final$dts2)
dfwideAll.Final$minute <- lubridate::minute(dfwideAll.Final$dts2)
dfwideAll.Final$HM <- dfwideAll.Final$hr + dfwideAll.Final$minute/60




dfWide.DECK <- dfwideAll.Final[which(is.na(dfwideAll.Final$diff_TempC) == F &
                                       is.na(dfwideAll.Final$tide_position2) == F),]
colnames(dfWide.DECK)[14] <- "Difference"
#colnames(dfWide.DECK)[7] <- "tide_position2"

bD.3 <- bam(Difference ~ te(DoY, HM, tide_position2, k = c(14,7,6), bs = c("cc","cc","cc")), data = dfWide.DECK)
vis.gam(bD.3,n.grid=50, theta=35, phi=32, zlab="", too.far=0.1) 
plot(bD.3)
gam.check(bD.3)
acf(residuals.gam(bD.3), ylab="", xlab="", main="")
dfpred.D <- expand.grid(DoY = seq(1,365,1),
                        HM = seq(0,23.75,0.25),
                        tide_position2 = seq(-0.9,0.9,0.3))#Depth_R = seq(0.2,1,0.4)
dfpred.D2 = predict(bD.3, newdata = dfpred.D, se.fit = TRUE)
dfpred.D$predvalues = predict(bD.3, newdata = dfpred.D)
dfpred.D$predvalues <- dfpred.D2[["fit"]][as.character(c(1:245280))]
dfpred.D$SEfit <- dfpred.D2[["se.fit"]][as.character(c(1:245280))]
dfpred.D$assessFit <- dfpred.D$SEfit/dfpred.D$predvalues
dfpred.D$Depth_R <- factor(dfpred.D$tide_position2, levels = c(seq(-0.9,0.9,0.3)), labels = c("Early Flood","Mid Flood","Late Flood","High Slack","Early Ebb","Mid Ebb","Late Ebb"))#factor(dfpred.D$Depth_R, levels = c(0.2,0.6,1))
dfpred.D$date <- as.Date(NA)
dfpred.D$date<- as.Date(dfpred.D$DoY, origin = '2019-05-31')
myPaletteContour <- colorRampPalette(rev(brewer.pal(6, "RdBu")))
plo_deck <- ggplot(dfpred.D, aes(x = DoY, y = HM, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 1) + 
  geom_text_contour(rotate = FALSE, binwidth = 1) +
  scale_y_continuous(breaks = c(seq(0,24,8)))+
  scale_fill_gradientn(colours = myPaletteContour(11),
                       name = "Difference in temperature (Restoration - Adj. Waterbody)")  +
  ylab("Hour")+
  xlab("Day of Year")+
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~ Depth_R) +
  theme_classic2()+
  theme(legend.position = "top")

plo_deck.fit <- ggplot(dfpred.D, aes(x = DoY, y = HM, z = SEfit, fill = SEfit)) + 
  geom_tile() + 
  geom_contour(binwidth = 0.025) + 
  geom_text_contour(rotate = FALSE, binwidth = 0.025) +
  scale_y_continuous(breaks = c(seq(0,24,8)))+
  scale_fill_gradientn(colours = myPaletteContour(11),
                       name = "Standard Error of Difference in temperature (Restoration - Adj. Waterbody)")  +
  ylab("Hour")+
  xlab("Day of Year")+
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~ Depth_R) +
  theme_classic2()+
  theme(legend.position = "top")



library(plyr)
dfwideAll.Final$date2 <- lubridate::date(dfwideAll.Final$dts2)
dfwideAll.Final$year2 <- lubridate::year(dfwideAll.Final$dts2)
dflong.D.r <- dfwideAll.Final[which(dfwideAll.Final$project== "Decker"),c("dts2","project","Restoration","Depth_R","date2","year2")]
dflong.D.a <- dfwideAll.Final[which(dfwideAll.Final$project== "Decker"),c("dts2","project","Adjacent","Depth_A","date2","year2")]
dflong.D.r$sitetype <- "Restoration"
dflong.D.a$sitetype <- "Adj. Waterbody"
colnames(dflong.D.r)[c(3,4)] <-c("TempC","Depth")
colnames(dflong.D.a)[c(3,4)] <-c("TempC","Depth")
dflong.D <- rbind(dflong.D.r,dflong.D.a)

dflong.F.r <- dfwideAll.Final[which(dfwideAll.Final$project== "Flyway"),c("dts2","project","Restoration","Depth_R","date2","year2")]
dflong.F.a <- dfwideAll.Final[which(dfwideAll.Final$project== "Flyway"),c("dts2","project","Adjacent","Depth_A","date2","year2")]
dflong.F.r$sitetype <- "Restoration"
dflong.F.a$sitetype <- "Adj. Waterbody"
colnames(dflong.F.r)[c(3,4)] <-c("TempC","Depth")
colnames(dflong.F.a)[c(3,4)] <-c("TempC","Depth")
dflong.F <- rbind(dflong.F.r,dflong.F.a)

dflong <- rbind(dflong.D, dflong.F)

test <- dflongTD[which(duplicated(dflongTD)==TRUE),]

summThresh.Diff <- ddply(dfwideAll[which(dfwideAll$year2 >2020),], c("project","date2"), summarise,
                         nTemp_R = length(Restoration),
                         nTemp_A = length(Adjacent),
                         oTemp_R = length(which(Restoration < 20)),
                         oTemp_A = length(which(Adjacent < 20)),
                         p_oTemp_R = oTemp_R/nTemp_R,
                         p_oTemp_A = oTemp_A/nTemp_A,
                         p_TimeDiff = p_oTemp_R - p_oTemp_A
                         )


summThresh <- ddply(dflong[which(dflong$year2 > 2020),], c("project","sitetype","date2"), summarise,
                    nTemp = length(TempC),
                    oTemp = length(which(TempC <20)),
                    #sTemp = length(threshTemp[which(threshTemp == "Suboptimal")]),
                    #mean20 = mean(TempC.20, na.rm = TRUE),
                    meanTemp = mean(TempC, na.rm = TRUE))
#summThresh$sitetype <- NA
#summThresh$sitetype[which(summThresh$Site %in% c("Decker Breach","Decker Pool","Yolo Flyway Farm"))] <- "Restoration"
#summThresh$sitetype[which(summThresh$Site %in% c("M13_USGS","SDI_USGS","TOED_USGS"))] <- "Adj. Waterbody"

#summThresh$nTempCheck <- ifelse(sum(summThresh$oTemp,summThresh$sTemp) == summThresh$nTemp, TRUE, FALSE)
summThresh$p_oTemp <- summThresh$oTemp/summThresh$nTemp
summThresh$project2 <- factor(summThresh$project, levels = c("Flyway","Decker"))
summThresh$sitetype2 <- factor(summThresh$sitetype, levels = c("Adj. Waterbody","Restoration"))

sum(summThresh$nTemp[which(summThresh$Site == "Yolo Flyway Farm")])
sum(summThresh$nTemp[which(summThresh$Site == "TOED_USGS")])
sum(summThresh$nTemp[which(summThresh$project == "Decker")])
sum(summThresh$nTemp[which(summThresh$project == "Decker" & summThresh$sitetype == "Restoration")])
sum(summThresh$nTemp[which(summThresh$project== "Decker" & summThresh$sitetype == "Adj. Waterbody")])

myPalette <- colorRampPalette(rev(brewer.pal(8, "Dark2")))
# use this bit to grab the legend from one plot, must turn off legend(theme) after using
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

heatDECK <- ggplot(summThresh[which(summThresh$project == "Decker"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\ntemperature was\n<20\u00b0C", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank()) 

legendT <- get_legend(heatDECK)
heatDECK <- heatDECK + theme(legend.position = "none")
heatFLYW <- ggplot(summThresh[which(summThresh$project == "Flyway"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  guides(fill=guide_legend(title="Proportion of time\ntemperature was\n<20\u00b0C", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5),
        legend.position = "none")

ggarrange(heatFLYW, heatDECK,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

myPaletteDiff <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "Decker")])
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "Flyway")])

summThresh.Diff$Difference <- "Difference"
heatDECK.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "Decker"),], aes(x = date2, y = project, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "Decker")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank()) 
legendT.Diff <- get_legend(heatDECK.diff)
heatDECK.diff <- heatDECK.diff + theme(legend.position = "none")
heatFLYW.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "Flyway"),], aes(x = date2, y = Difference, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "Decker")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5), 
        legend.position = "none") 

ggarrange(heatFLYW.diff, heatDECK.diff,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

ggarrange(heatFLYW, heatDECK, legendT,
          heatFLYW.diff, heatDECK.diff, legendT.Diff,
          ncol = 3, nrow = 2,
          align = "h",
          widths = c(2,2,0.8))
################################################################################
```