---
title: "Analyses for Ch1 of Big Report"
author: "DMC"
date: "2023-09-18"
---

Here is the script for performing GAM with anomaly.

# Temperature
For Temperature (hourly)
```{r}
library(plyr)
library(ggplot2)
library(scales)
library(gridExtra)
library(metR)
library(ggpubr)
library(RColorBrewer)

rm(list = ls())

load(here::here("working","MergedHourly_4Tide.RData"))
'%ni%' <- Negate('%in%')


df_DECK.m$dts2 <- df_DECK.m$dateTime
df_DECK.m <- df_DECK.m[order(df_DECK.m$dts2),(!colnames(df_DECK.m) %in% c("depth"))]

df_FLYW.m$dts2 <- df_FLYW.m$dateTime
df_FLYW.m <- df_FLYW.m[order(df_FLYW.m$dts2),]



dfwideAll <- rbind.data.frame(df_DECK.m[which(is.na(df_DECK.m$diff_TempC)==F),],
                              df_FLYW.m[which(is.na(df_FLYW.m$diff_TempC)==F),])
dfwideAll$Difference <- dfwideAll$diff_TempC
dfwideAll$Restoration <- as.numeric(dfwideAll$TempC.RESTO)
dfwideAll$Adjacent <- as.numeric(dfwideAll$TempC.ADJ) 
dfwideAll$project <- dfwideAll$Station.RESTO
ggplot(dfwideAll, aes(dts2, Difference)) + geom_point() + facet_grid(project ~., scales = "free_y")


dfwideAll$hr <- lubridate::hour(dfwideAll$dts2)
dfwideAll$DoY <- lubridate::yday(dfwideAll$dts2)


library(mgcv)
dfwideDECK <- dfwideAll[which(dfwideAll$project == "DECK"),]
bD.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideDECK)
#bD.2.1 <- bam(Restoration ~ te(DoY, hr, k = c(14,8), bs = c("cc","cc")), data = dfwideDECK.4)
#anova(bD.2,bD.2.1)
plot(bD.2)
gam.check(bD.2)
dfwideDECK$resAnom <- residuals(bD.2, type = "response")
#dfwideDECK.4$resAnom.1 <- residuals(bD.2.1, type = "response")

bD.3 <- bam(Difference ~ te(DoY, hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK)
#bD.3.1 <- bam(Difference ~ te(DoY, hr, resAnom.1, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK.4)
plot(bD.3)
gam.check(bD.3)
#anova(bD.3,bD.3.1)
range(dfwideDECK$resAnom)

dfpred.D <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-3,3,3))
dfpred.D$predvalues = predict(bD.3, newdata = dfpred.D)
range(dfpred.D$predvalues)


dfwideFLYW <- dfwideAll[which(dfwideAll$project == "FLYW"),]

bF.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideFLYW)
plot(bF.2)
gam.check(bF.2)
dfwideFLYW$resAnom <- residuals(bF.2, type = "response")

bF.3 <- bam(Difference ~ te(DoY,hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideFLYW)
plot(bF.3)
gam.check(bF.3)

range(dfwideFLYW$resAnom)

dfpred.F <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-3,3,3))
dfpred.F$predvalues = predict(bF.3, newdata = dfpred.F)
range(dfpred.F$predvalues)

myPaletteContour <- colorRampPalette(rev(brewer.pal(6, "RdBu")))
plo_deck <- ggplot(dfpred.D, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 1) + 
  geom_text_contour(rotate = FALSE, binwidth = 1) +
  scale_fill_gradientn(colours = myPaletteContour(5),
                       limits=c(range(dfpred.D$predvalues)[1],range(dfpred.F$predvalues)[2]),
                       name = "Difference in temperature (Restoration - Adj. Waterbody)") +
  ylab("Decker Island\nHour") +
  xlab("Day of Year") +
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~resAnom) +
  theme_classic2()+
  theme(strip.text = element_blank()) +
  theme(plot.margin = unit(c(0,0,0,0), "cm"))

plo_flyw <- ggplot(dfpred.F, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 1) + 
  geom_text_contour(rotate = FALSE, binwidth = 0.5) +
  scale_fill_gradientn(colours = myPaletteContour(11),
                       limits=c(range(dfpred.D$predvalues)[1],range(dfpred.F$predvalues)[2]),
                       name = "Difference in temperature (Restoration - Adj. Waterbody)") +
  ylab("Yolo Flyway Farms\nHour")+
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~ resAnom) +
  theme_classic2()+
  theme(plot.margin = unit(c(0,0,0,0), "cm"),
        axis.title.x = element_blank())


plo_F.D <- ggarrange(plo_flyw, plo_deck, 
                     ncol = 1, nrow = 2,
                     common.legend = TRUE, legend = "top",
                     align = "hv")
ggsave(paste("GAM_TempAnom",".png",sep = ""), path = here::here("figures","publication"), plo_F.D, width = 1600, height = 1080, dpi = 192, units = "px", bg="white")

library(plyr)
dfwideAll$date2 <- lubridate::date(dfwideAll$dts2)
dfwideAll$year2 <- lubridate::year(dfwideAll$dts2)
dflong.D.r <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Restoration","date2","year2")]
dflong.D.a <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Adjacent","date2","year2")]
dflong.D.r$sitetype <- "Restoration"
dflong.D.a$sitetype <- "Adj. Waterbody"
colnames(dflong.D.r)[3] <-"TempC"
colnames(dflong.D.a)[3] <-"TempC"
dflong.D <- rbind(dflong.D.r,dflong.D.a)

dflong.F.r <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Restoration","date2","year2")]
dflong.F.a <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Adjacent","date2","year2")]
dflong.F.r$sitetype <- "Restoration"
dflong.F.a$sitetype <- "Adj. Waterbody"
colnames(dflong.F.r)[3] <-"TempC"
colnames(dflong.F.a)[3] <-"TempC"
dflong.F <- rbind(dflong.F.r,dflong.F.a)

dflong <- rbind(dflong.D, dflong.F)

summThresh.Diff <- ddply(dfwideAll, c("project","date2"), summarise,
                         nTemp_R = length(Restoration),
                         nTemp_A = length(Adjacent),
                         oTemp_R = length(which(Restoration < 20)),
                         oTemp_A = length(which(Adjacent < 20)),
                         p_oTemp_R = oTemp_R/nTemp_R,
                         p_oTemp_A = oTemp_A/nTemp_A,
                         p_TimeDiff = p_oTemp_R - p_oTemp_A
                         )


summThresh <- ddply(dflong, c("project","sitetype","date2"), summarise,
                    nTemp = length(TempC),
                    oTemp = length(which(TempC <20)),
                    #sTemp = length(threshTemp[which(threshTemp == "Suboptimal")]),
                    #mean20 = mean(TempC.20, na.rm = TRUE),
                    meanTemp = mean(TempC, na.rm = TRUE))
#summThresh$sitetype <- NA
#summThresh$sitetype[which(summThresh$Site %in% c("Decker Breach","Decker Pool","Yolo Flyway Farm"))] <- "Restoration"
#summThresh$sitetype[which(summThresh$Site %in% c("M13_USGS","SDI_USGS","TOED_USGS"))] <- "Adj. Waterbody"

#summThresh$nTempCheck <- ifelse(sum(summThresh$oTemp,summThresh$sTemp) == summThresh$nTemp, TRUE, FALSE)
summThresh$p_oTemp <- summThresh$oTemp/summThresh$nTemp
summThresh$project2 <- factor(summThresh$project, levels = c("FLYW","DECK"))
summThresh$sitetype2 <- factor(summThresh$sitetype, levels = c("Adj. Waterbody","Restoration"))

# sum(summThresh$nTemp[which(summThresh$Site == "Yolo Flyway Farm")])
# sum(summThresh$nTemp[which(summThresh$Site == "TOED_USGS")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker" & summThresh$sitetype == "Restoration")])
# sum(summThresh$nTemp[which(summThresh$project== "Decker" & summThresh$sitetype == "Adj. Waterbody")])

myPalette <- colorRampPalette(rev(brewer.pal(8, "Dark2")))
# use this bit to grab the legend from one plot, must turn off legend(theme) after using
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

heatDECK <- ggplot(summThresh[which(summThresh$project == "DECK"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\ntemperature was\n<20\u00b0C", reverse = TRUE)) +
  theme_classic2() + 
  ggtitle("Decker Island")+
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 

legendT <- get_legend(heatDECK)
heatDECK <- heatDECK + theme(legend.position = "none")
heatFLYW <- ggplot(summThresh[which(summThresh$project == "FLYW"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  scale_y_discrete(labels = c("Adj. Waterbody       ", "    Restoration")) + 
  guides(fill=guide_legend(title="Proportion of time\ntemperature was\n<20\u00b0C", reverse = TRUE)) +
  theme_classic2() + 
  ggtitle("Yolo Flyway Farms")+
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5),
        legend.position = "none")

ggarrange(heatFLYW, heatDECK,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

myPaletteDiff <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "DECK")])
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "FLYW")])

summThresh.Diff$Difference <- "Difference"
heatDECK.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "DECK"),], aes(x = date2, y = project, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "DECK")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 
legendT.Diff <- get_legend(heatDECK.diff)
heatDECK.diff <- heatDECK.diff + theme(legend.position = "none")
heatFLYW.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "FLYW"),], aes(x = date2, y = Difference, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "DECK")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5), 
        legend.position = "none") 

ggarrange(heatFLYW.diff, heatDECK.diff,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

plo_temp.F.D <- ggarrange(heatFLYW, heatDECK, legendT,
                          heatFLYW.diff, heatDECK.diff, legendT.Diff,
                          ncol = 3, nrow = 2,
                          align = "hv",
                          widths = c(2,2,0.8))

ggsave(paste("Heatmap_Temp",".png",sep = ""), path = here::here("figures","publication"), plo_temp.F.D, width = 1600, height = 1080, dpi = 192, units = "px", bg="white")
```

# Turbidity

For Turbidity
```{r}
rm(list = ls())

load(here::here("working","MergedHourly_4Tide.RData"))
'%ni%' <- Negate('%in%')


df_DECK.m$dts2 <- df_DECK.m$dateTime
df_DECK.m <- df_DECK.m[order(df_DECK.m$dts2),(!colnames(df_DECK.m) %in% c("depth"))]

df_FLYW.m$dts2 <- df_FLYW.m$dateTime
df_FLYW.m <- df_FLYW.m[order(df_FLYW.m$dts2),]



dfwideAll <- rbind.data.frame(df_DECK.m,
                              df_FLYW.m)

dfwideAll$Restoration <- as.numeric(dfwideAll$turb.RESTO)
dfwideAll$Adjacent <- as.numeric(dfwideAll$turb.ADJ) 
dfwideAll$Difference <- dfwideAll$Restoration - dfwideAll$Adjacent
dfwideAll$project <- dfwideAll$Station.RESTO
dfwideAll <- dfwideAll[which(is.na(dfwideAll$Difference)==F),]


dfwideAll$hr <- lubridate::hour(dfwideAll$dts2)
dfwideAll$DoY <- lubridate::yday(dfwideAll$dts2)


library(mgcv)
dfwideDECK <- dfwideAll[which(dfwideAll$project == "DECK"),]
bD.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideDECK)
#bD.2.1 <- bam(Restoration ~ te(DoY, hr, k = c(14,8), bs = c("cc","cc")), data = dfwideDECK.4)
#anova(bD.2,bD.2.1)
plot(bD.2)
gam.check(bD.2)
dfwideDECK$resAnom <- residuals(bD.2, type = "response")
#dfwideDECK.4$resAnom.1 <- residuals(bD.2.1, type = "response")

bD.3 <- bam(Difference ~ te(DoY, hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK)
#bD.3.1 <- bam(Difference ~ te(DoY, hr, resAnom.1, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK.4)
plot(bD.3)
gam.check(bD.3)
#anova(bD.3,bD.3.1)
range(dfwideDECK$resAnom)

dfpred.D <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-10,10,10))
dfpred.D$predvalues = predict(bD.3, newdata = dfpred.D)
range(dfpred.D$predvalues)

myPaletteContour <- colorRampPalette(rev(brewer.pal(6, "RdBu")))
plo_deck <- ggplot(dfpred.D, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 5) + 
  geom_text_contour(rotate = FALSE, binwidth = 5) +
  scale_fill_gradientn(colours = myPaletteContour(5)) +#,
                       #limits=c(range(dfpred.D$predvalues)[1],range(dfpred.F$predvalues)[2]),
                       #name = "delTurb") +
  ylab("Decker Island\nHour") +
  xlab("Day of Year") +
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~resAnom) +
  theme_classic2()+
  theme(strip.text = element_blank()) 


dfwideFLYW <- dfwideAll[which(dfwideAll$project == "FLYW"),]
bF.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideFLYW)
plot(bF.2)
gam.check(bF.2)
dfwideFLYW$resAnom <- residuals(bF.2, type = "response")

bF.3 <- bam(Difference ~ te(DoY,hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideFLYW)
plot(bF.3)
gam.check(bF.3)

range(dfwideFLYW$resAnom)

dfpred.F <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-10,10,10))
dfpred.F$predvalues = predict(bF.3, newdata = dfpred.F)
range(dfpred.F$predvalues)


plo_flyw <- ggplot(dfpred.F, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 1) + 
  geom_text_contour(rotate = FALSE, binwidth = 0.5) +
  scale_fill_gradientn(colours = myPaletteContour(11),
                       limits=c(range(dfpred.F$predvalues)[1],range(dfpred.D$predvalues)[2]),
                       name = "Difference in temperature (Restoration - Adj. Waterbody)") +
  ylab("Yolo Flyway Farms\nHour")+
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~ resAnom) +
  theme_classic2()


# ggarrange(plo_flyw + rremove("xlab"), plo_deck, 
#           ncol = 1, nrow = 2,
#           common.legend = TRUE, legend = "top",
#           align = "hv")


library(plyr)
dfwideAll$date2 <- lubridate::date(dfwideAll$dts2)
dfwideAll$year2 <- lubridate::year(dfwideAll$dts2)
dflong.D.r <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Restoration","date2","year2")]
dflong.D.a <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Adjacent","date2","year2")]
dflong.D.r$sitetype <- "Restoration"
dflong.D.a$sitetype <- "Adj. Waterbody"
colnames(dflong.D.r)[3] <-"TempC"
colnames(dflong.D.a)[3] <-"TempC"
dflong.D <- rbind(dflong.D.r,dflong.D.a)

dflong.F.r <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Restoration","date2","year2")]
dflong.F.a <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Adjacent","date2","year2")]
dflong.F.r$sitetype <- "Restoration"
dflong.F.a$sitetype <- "Adj. Waterbody"
colnames(dflong.F.r)[3] <-"TempC"
colnames(dflong.F.a)[3] <-"TempC"
dflong.F <- rbind(dflong.F.r,dflong.F.a)

dflong <- rbind(dflong.D, dflong.F)

summThresh.Diff <- ddply(dfwideAll[which(dfwideAll$year2 >2020),], c("project","date2"), summarise,
                         nTemp_R = length(Restoration),
                         nTemp_A = length(Adjacent),
                         oTemp_R = length(which(Restoration >12 & Restoration <80)),
                         oTemp_A = length(which(Adjacent >12 & Adjacent <80)),
                         p_oTemp_R = oTemp_R/nTemp_R,
                         p_oTemp_A = oTemp_A/nTemp_A,
                         p_TimeDiff = p_oTemp_R - p_oTemp_A00
                         )


summThresh <- ddply(dflong[which(dflong$year2 > 2020),], c("project","sitetype","date2"), summarise,
                    nTemp = length(TempC),
                    oTemp = length(which(TempC >12 & TempC < 80)),
                    #sTemp = length(threshTemp[which(threshTemp == "Suboptimal")]),
                    #mean20 = mean(TempC.20, na.rm = TRUE),
                    meanTemp = mean(TempC, na.rm = TRUE))
#summThresh$sitetype <- NA
#summThresh$sitetype[which(summThresh$Site %in% c("Decker Breach","Decker Pool","Yolo Flyway Farm"))] <- "Restoration"
#summThresh$sitetype[which(summThresh$Site %in% c("M13_USGS","SDI_USGS","TOED_USGS"))] <- "Adj. Waterbody"

#summThresh$nTempCheck <- ifelse(sum(summThresh$oTemp,summThresh$sTemp) == summThresh$nTemp, TRUE, FALSE)
summThresh$p_oTemp <- summThresh$oTemp/summThresh$nTemp
summThresh$project2 <- factor(summThresh$project, levels = c("FLYW","DECK"))
summThresh$sitetype2 <- factor(summThresh$sitetype, levels = c("Adj. Waterbody","Restoration"))

# sum(summThresh$nTemp[which(summThresh$Site == "Yolo Flyway Farm")])
# sum(summThresh$nTemp[which(summThresh$Site == "TOED_USGS")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker" & summThresh$sitetype == "Restoration")])
# sum(summThresh$nTemp[which(summThresh$project== "Decker" & summThresh$sitetype == "Adj. Waterbody")])

myPalette <- colorRampPalette(rev(brewer.pal(8, "Dark2")))
# use this bit to grab the legend from one plot, must turn off legend(theme) after using
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

heatDECK <- ggplot(summThresh[which(summThresh$project == "DECK"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\ntemperature was\n12< x >80", reverse = TRUE)) +
  ggtitle("Decker Island")+
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 

legendT <- get_legend(heatDECK)
heatDECK <- heatDECK + theme(legend.position = "none")
heatFLYW <- ggplot(summThresh[which(summThresh$project == "FLYW"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  scale_y_discrete(labels = c("Adj. Waterbody       ", "    Restoration")) +
  guides(fill=guide_legend(title="Proportion of time\nturbidity was\n12< x >80", reverse = TRUE)) +
  ggtitle("Yolo Flyway Farms") +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5),
        legend.position = "none")

ggarrange(heatFLYW, heatDECK,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

myPaletteDiff <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "DECK")])
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "FLYW")])

summThresh.Diff$Difference <- "Difference"
heatDECK.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "DECK"),], aes(x = date2, y = project, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(-1,1)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 
legendT.Diff <- get_legend(heatDECK.diff)
heatDECK.diff <- heatDECK.diff + theme(legend.position = "none")
heatFLYW.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "FLYW"),], aes(x = date2, y = Difference, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(-1,1)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5), 
        legend.position = "none") 

ggarrange(heatFLYW.diff, heatDECK.diff,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

ggarrange(heatFLYW, heatDECK, legendT,
          heatFLYW.diff, heatDECK.diff +rremove("legend"), legendT.Diff,
          ncol = 3, nrow = 2,
          align = "h",
          widths = c(2,2,0.8))
################################################################################
```

# Dissolved Oxygen

For DO
```{r}
library(plyr)
library(ggplot2)
library(scales)
library(gridExtra)
library(metR)
library(ggpubr)
library(RColorBrewer)

rm(list = ls())

load(here::here("working","MergedHourly_4Tide.RData"))
'%ni%' <- Negate('%in%')


df_DECK.m$dts2 <- df_DECK.m$dateTime
df_DECK.m <- df_DECK.m[order(df_DECK.m$dts2),(!colnames(df_DECK.m) %in% c("depth"))]

df_FLYW.m$dts2 <- df_FLYW.m$dateTime
df_FLYW.m <- df_FLYW.m[order(df_FLYW.m$dts2),]



dfwideAll <- rbind.data.frame(df_DECK.m,
                              df_FLYW.m)

dfwideAll$Restoration <- as.numeric(dfwideAll$do.RESTO)
dfwideAll$Adjacent <- as.numeric(dfwideAll$do.ADJ) 
dfwideAll$Difference <- dfwideAll$Restoration - dfwideAll$Adjacent
dfwideAll$project <- dfwideAll$Station.RESTO
dfwideAll <- dfwideAll[which(is.na(dfwideAll$Difference)==F),]


dfwideAll$hr <- lubridate::hour(dfwideAll$dts2)
dfwideAll$DoY <- lubridate::yday(dfwideAll$dts2)

library(mgcv)
dfwideDECK <- dfwideAll[which(dfwideAll$project == "DECK"),]
bD.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideDECK)
#bD.2.1 <- bam(Restoration ~ te(DoY, hr, k = c(14,8), bs = c("cc","cc")), data = dfwideDECK.4)
#anova(bD.2,bD.2.1)
plot(bD.2)
gam.check(bD.2)
dfwideDECK$resAnom <- residuals(bD.2, type = "response")
#dfwideDECK.4$resAnom.1 <- residuals(bD.2.1, type = "response")

bD.3 <- bam(Difference ~ te(DoY, hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK)
#bD.3.1 <- bam(Difference ~ te(DoY, hr, resAnom.1, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideDECK.4)
plot(bD.3)
gam.check(bD.3)
#anova(bD.3,bD.3.1)
range(dfwideDECK$resAnom)

dfpred.D <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-3,3,3))
dfpred.D$predvalues = predict(bD.3, newdata = dfpred.D)
range(dfpred.D$predvalues)

myPaletteContour <- colorRampPalette(rev(brewer.pal(6, "RdBu")))
plo_deck <- ggplot(dfpred.D, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 5) + 
  geom_text_contour(rotate = FALSE, binwidth = 5) +
  scale_fill_gradientn(colours = myPaletteContour(5)) +#,
                       #limits=c(range(dfpred.D$predvalues)[1],range(dfpred.F$predvalues)[2]),
                       #name = "delTurb") +
  ylab("Decker Island\nHour") +
  xlab("Day of Year") +
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~resAnom) +
  theme_classic2()+
  theme(strip.text = element_blank()) 


dfwideFLYW <- dfwideAll[which(dfwideAll$project == "FLYW"),]
bF.2 <- bam(Restoration ~ te(DoY, hr, k = c(5,5), bs = c("cc","cc")), data = dfwideFLYW)
plot(bF.2)
gam.check(bF.2)
dfwideFLYW$resAnom <- residuals(bF.2, type = "response")

bF.3 <- bam(Difference ~ te(DoY,hr, resAnom, k = c(14,7,6), bs = c("cc","cc","tp")), data = dfwideFLYW)
plot(bF.3)
gam.check(bF.3)

range(dfwideFLYW$resAnom)

dfpred.F <- expand.grid(hr = seq(0,23,1),
                      DoY = seq(1,365,1),
                      resAnom = seq(-3,3,3))
dfpred.F$predvalues = predict(bF.3, newdata = dfpred.F)
range(dfpred.F$predvalues)

plo_flyw <- ggplot(dfpred.F, aes(x = DoY, y = hr, z = predvalues, fill = predvalues)) + 
  geom_tile() + 
  geom_contour(binwidth = 1) + 
  geom_text_contour(rotate = FALSE, binwidth = 0.5) +
  scale_fill_gradientn(colours = myPaletteContour(11),
                       limits=c(range(dfpred.D$predvalues)[1],range(dfpred.F$predvalues)[2]),
                       name = "Difference in temperature (Restoration - Adj. Waterbody)") +
  ylab("Yolo Flyway Farms\nHour")+
  #guides(fill=guide_legend(title="Difference in temperature (Restoration - Adj. Waterbody)")) +
  facet_grid(.~ resAnom) +
  theme_classic2()


ggarrange(plo_flyw + rremove("xlab"), plo_deck, 
          ncol = 1, nrow = 2,
          common.legend = TRUE, legend = "top",
          align = "hv")


library(plyr)
dfwideAll$date2 <- lubridate::date(dfwideAll$dts2)
dfwideAll$year2 <- lubridate::year(dfwideAll$dts2)
dflong.D.r <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Restoration","date2","year2")]
dflong.D.a <- dfwideAll[which(dfwideAll$project== "DECK"),c("dts2","project","Adjacent","date2","year2")]
dflong.D.r$sitetype <- "Restoration"
dflong.D.a$sitetype <- "Adj. Waterbody"
colnames(dflong.D.r)[3] <-"TempC"
colnames(dflong.D.a)[3] <-"TempC"
dflong.D <- rbind(dflong.D.r,dflong.D.a)

dflong.F.r <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Restoration","date2","year2")]
dflong.F.a <- dfwideAll[which(dfwideAll$project== "FLYW"),c("dts2","project","Adjacent","date2","year2")]
dflong.F.r$sitetype <- "Restoration"
dflong.F.a$sitetype <- "Adj. Waterbody"
colnames(dflong.F.r)[3] <-"TempC"
colnames(dflong.F.a)[3] <-"TempC"
dflong.F <- rbind(dflong.F.r,dflong.F.a)

dflong <- rbind(dflong.D, dflong.F)

summThresh.Diff <- ddply(dfwideAll[which(dfwideAll$year2 >2020),], c("project","date2"), summarise,
                         nTemp_R = length(Restoration),
                         nTemp_A = length(Adjacent),
                         oTemp_R = length(which(Restoration >5)),
                         oTemp_A = length(which(Adjacent >5)),
                         p_oTemp_R = oTemp_R/nTemp_R,
                         p_oTemp_A = oTemp_A/nTemp_A,
                         p_TimeDiff = p_oTemp_R - p_oTemp_A
                         )


summThresh <- ddply(dflong[which(dflong$year2 > 2020),], c("project","sitetype","date2"), summarise,
                    nTemp = length(TempC),
                    oTemp = length(which(TempC >5)),
                    #sTemp = length(threshTemp[which(threshTemp == "Suboptimal")]),
                    #mean20 = mean(TempC.20, na.rm = TRUE),
                    meanTemp = mean(TempC, na.rm = TRUE))
#summThresh$sitetype <- NA
#summThresh$sitetype[which(summThresh$Site %in% c("Decker Breach","Decker Pool","Yolo Flyway Farm"))] <- "Restoration"
#summThresh$sitetype[which(summThresh$Site %in% c("M13_USGS","SDI_USGS","TOED_USGS"))] <- "Adj. Waterbody"

#summThresh$nTempCheck <- ifelse(sum(summThresh$oTemp,summThresh$sTemp) == summThresh$nTemp, TRUE, FALSE)
summThresh$p_oTemp <- summThresh$oTemp/summThresh$nTemp
summThresh$project2 <- factor(summThresh$project, levels = c("Flyway","Decker"))
summThresh$sitetype2 <- factor(summThresh$sitetype, levels = c("Adj. Waterbody","Restoration"))

# sum(summThresh$nTemp[which(summThresh$Site == "Yolo Flyway Farm")])
# sum(summThresh$nTemp[which(summThresh$Site == "TOED_USGS")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker")])
# sum(summThresh$nTemp[which(summThresh$project == "Decker" & summThresh$sitetype == "Restoration")])
# sum(summThresh$nTemp[which(summThresh$project== "Decker" & summThresh$sitetype == "Adj. Waterbody")])

myPalette <- colorRampPalette(rev(brewer.pal(8, "Dark2")))
# use this bit to grab the legend from one plot, must turn off legend(theme) after using
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

heatDECK <- ggplot(summThresh[which(summThresh$project == "DECK"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\ndissolved oxygen\nwas >5 mg/L", reverse = TRUE)) +
  ggtitle("Decker Island") +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 

legendT <- get_legend(heatDECK)
heatDECK <- heatDECK + theme(legend.position = "none")
heatFLYW <- ggplot(summThresh[which(summThresh$project == "FLYW"),], aes(x = date2, y = sitetype2, fill = p_oTemp)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPalette(5)) +
  scale_y_discrete(labels = c("Adj. Waterbody       ", "    Restoration")) +
  guides(fill=guide_legend(title="Proportion of time\ndissolved oxygen\nwas >5 mg/L", reverse = TRUE)) +
  ggtitle("Yolo Flyway Farms") +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5),
        legend.position = "none")

ggarrange(heatFLYW, heatDECK,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

myPaletteDiff <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "DECK")])
range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "FLYW")])

summThresh.Diff$Difference <- "Difference"
heatDECK.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "DECK"),], aes(x = date2, y = project, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "FLYW")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 10)) 
legendT.Diff <- get_legend(heatDECK.diff)
heatDECK.diff <- heatDECK.diff + theme(legend.position = "none")
heatFLYW.diff <- ggplot(summThresh.Diff[which(summThresh.Diff$project == "FLYW"),], aes(x = date2, y = Difference, fill = p_TimeDiff)) + 
  geom_tile() +
  scale_fill_gradientn(colours = myPaletteDiff(11),limits=c(range(summThresh.Diff$p_TimeDiff[which(summThresh.Diff$project == "FLYW")]))) +
  xlab("Date") +
  guides(fill=guide_legend(title="Proportion of time\nRestoration is\nmore suitable", reverse = TRUE)) +
  theme_classic2() + 
  theme(axis.title = element_blank(),
        axis.text.y = element_text(angle =90, hjust = 0.5), 
        legend.position = "none") 

ggarrange(heatFLYW.diff, heatDECK.diff,
          ncol = 2, nrow = 1,
          common.legend = TRUE, legend = "right",
          align = "hv"
          )

ggarrange(heatFLYW, heatDECK, legendT,
          heatFLYW.diff, heatDECK.diff +rremove("legend"), legendT.Diff,
          ncol = 3, nrow = 2,
          align = "h",
          widths = c(2,2,0.8))
################################################################################
```

