For data from USGS Decker station near Decker Island
```{r get Decker ext stn data}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455478"
parameterCd <- "00065" # Discharge
startDate <- "2019-01-01T00:00"
endDate <- "2022-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("imports","ExtPrograms","USGS","USGS_parameters.csv"))

# dailyDataAvailable <- whatNWISdata(
#  siteNumber = siteNumber,
#  service = "iv"
# )
# dailyDataAvailable$parameter <- NA
# dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
# siteINFO <- readNWISsite(siteNumber)
# siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)
# 
# save(siteAll, file = here::here("working", "USGS_11455478.RData"))

load(here::here("working", "USGS_11455478.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_DECKUSGS <- siteAll[,c(2,3,8,9, # 14 and 15 are DO and its QC status
                        which(colnames(siteAll) %in% col2get2[c(1,2, #temperature of upper sonde and its QC status
                                                                    3,4,# SC of upper sonde and its QC status
                                                                    13,14) # turb of upper sonde and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_DECKUSGS)[3:10] <- c("DOmgL","DO_flag","TempC","TempC_flag","SPC","SPC_flag","Turb","Turb_flag")

save(df_DECKUSGS, file = here::here("working", "USGS_Decker.RData"))
```

For data from USGS Toland station near Decker Island
```{r get Toland data}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455485"
parameterCd <- "00065" # Discharge
startDate <- "2019-01-01T00:00"
endDate <- "2022-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("imports","ExtPrograms","USGS","USGS_parameters.csv"))

# dailyDataAvailable <- whatNWISdata(
#  siteNumber = siteNumber,
#  service = "iv"
# )
# dailyDataAvailable$parameter <- NA
# dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
# siteINFO <- readNWISsite(siteNumber)
# siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)
# 
# save(siteAll, file = here::here("working", "USGS_11455485.RData"))

load(here::here("working", "USGS_11455485.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_Toland <- siteAll[,c(2,3,14,15, # 14 and 15 are DO and its QC status
                        which(colnames(siteAll) %in% col2get2[c(3,4, #temperature of upper sonde and its QC status
                                                                    8,9,# SC of upper sonde and its QC status
                                                                    17,20) # turb of upper sonde and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_Toland)[3:10] <- c("DOmgL","DO_flag","TempC","TempC_flag","SPC","SPC_flag","Turb","Turb_flag")

save(df_Toland, file = here::here("working", "USGS_Toland.RData"))
```

For 2022 data from USGS Toe Drain station near Yolo Flyway Farms
```{r get Toe Drain}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455140"
parameterCd <- "00065" # Discharge
startDate <- "2019-01-01T00:00"
endDate <- "2022-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("imports","ExtPrograms","USGS","USGS_parameters.csv"))

# dailyDataAvailable <- whatNWISdata(
#  siteNumber = siteNumber,
#  service = "iv"
# )
# dailyDataAvailable$parameter <- NA
# dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
# siteINFO <- readNWISsite(siteNumber)
# siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)
# 
# save(siteAll, file = here::here("working", "USGS_11455140.RData"))

load(here::here("working", "USGS_11455140.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_ToeDrain <- siteAll[,c(2,3,12,13, # 12 and 13 are DO and its QC status
                          which(colnames(siteAll) %in% col2get2[c(1,2, #temperature of upper sonde and its QC status
                                                                    8,7,# SC of upper sonde and its QC status
                                                                    17,18)# turb of upper sonde and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_ToeDrain)[3:10] <- c("DOmgL","DO_flag","TempC","TempC_flag","SPC","SPC_flag","Turb","Turb_flag")

save(df_ToeDrain, file = here::here("working", "USGS_ToeDrain.RData"))
```

```{r make 1 DeckerExt dataset}
library(ggplot2)

rm(list = ls())
'%ni%' = Negate('%in%')

load(here::here("working","USGS_Decker.RData"))
load(here::here("working","USGS_Toland.RData"))

USGS_DECK <- rbind.data.frame(df_DECKUSGS,df_Toland)

plo <- ggplot(USGS_DECK, aes(x = dateTime, y = tempC)) +
  geom_point() +
  facet_grid(site_no ~.)

range(df_Toland$dateTime, na.rm = T)

#df_DECKUSGS.2 <- df_DECKUSGS[which(df_DECKUSGS$dateTime %ni% df_Toland$dateTime),]
df_DECKUSGS.2 <- df_DECKUSGS[which(df_DECKUSGS$dateTime < as.POSIXct(strptime(range(df_Toland$dateTime, na.rm = T)[1], format = "%Y-%m-%d %H:%M:%S", tz = "America/Los_Angeles"))),]

USGS_DECK.2 <- rbind.data.frame(df_DECKUSGS.2,df_Toland)

plo <- ggplot(USGS_DECK.2, aes(x = dateTime, y = tempC)) +
  geom_point() +
  facet_grid(site_no ~.)

save(USGS_DECK.2, file = here::here("working","USGS_DeckerTogether.Rds"))
```