---
title: "ExtProgram_Data"
author: "DMC"
date: "8/1/2024"
output: html_document
---

For 2023 data from USGS Toland station near Decker Island
```{r}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455485"
parameterCd <- "00065" # Discharge
startDate <- "2023-01-01T00:00"
endDate <- "2023-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("raw","ExtPrograms","USGS","USGS_parameters.csv"))

dailyDataAvailable <- whatNWISdata(
 siteNumber = siteNumber,
 service = "iv"
)
dailyDataAvailable$parameter <- NA
dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
siteINFO <- readNWISsite(siteNumber)
siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)

#save(siteAll, file = here::here("working", "USGS_11455485.RData"))

#load(here::here("working", "USGS_11455485.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_Toland <- siteAll[,c(2,3,14,15, # 14 and 15 are DO and its QC status
                        which(colnames(siteAll) %in% col2get2[c(3,4, #temperature of upper sonde and its QC status
                                                                    8,9,# SC of upper sonde and its QC status
                                                                    13,14,# fdom of upper sonde and its QC status
                                                                    15,16,# chl of upper sonde and its QC status
                                                                    17,20) # turb of upper sonde and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_Toland)[3:14] <- c("do","do_flag","tempC","tempC_flag","sc","sc_flag","fdom","fdom_flag","chl","chl_flag","turb","turb_flag")

save(df_Toland, file = here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Toland.RData"))
```

For 2023 data from USGS Toe Drain station near Yolo Flyway Farms
```{r}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455140"
parameterCd <- "00065" # Discharge
startDate <- "2023-01-01T00:00"
endDate <- "2023-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("raw","ExtPrograms","USGS","USGS_parameters.csv"))

dailyDataAvailable <- whatNWISdata(
 siteNumber = siteNumber,
 service = "iv"
)
dailyDataAvailable$parameter <- NA
dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
siteINFO <- readNWISsite(siteNumber)
siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)

#save(siteAll, file = here::here("working", "USGS_11455485.RData"))

#load(here::here("working", "USGS_11455485.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_ToeDrain <- siteAll[,c(2,3,12,13, # 12 and 13 are DO and its QC status
                          which(colnames(siteAll) %in% col2get2[c(1,2, #temperature of upper sonde and its QC status
                                                                    7,8,# SC of upper sonde and its QC status
                                                                    13,14,# fdom of upper sonde and its QC status
                                                                    15,16,# chl of upper sonde and its QC status
                                                                    17,18,# turb of upper sonde and its QC status
                                                                    9,10,# pH and its QC status
                                                                    5,6) # gage height and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_ToeDrain)[3:18] <- c("do","do_flag","tempC","tempC_flag","gage","gage_flag","sc","sc_flag", "pH","pH_flag","fdom","fdom_flag","chl","chl_flag","turb","turb_flag")

save(df_ToeDrain, file = here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_ToeDrain.RData"))
```

For 2023 data from USGS Liberty Island station near Yolo Flyway Farms
```{r}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "11455315"
parameterCd <- "00065" # Discharge
startDate <- "2023-01-01T00:00"
endDate <- "2023-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("raw","ExtPrograms","USGS","USGS_parameters.csv"))

dailyDataAvailable <- whatNWISdata(
 siteNumber = siteNumber,
 service = "iv"
)
dailyDataAvailable$parameter <- NA
dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
siteINFO <- readNWISsite(siteNumber)
siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)

#save(siteAll, file = here::here("working", "USGS_11455485.RData"))

#load(here::here("working", "USGS_11455485.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_Liberty <- siteAll[,c(2,3,12,13,# 12 and 13 are DO and its QC status
                         which(colnames(siteAll) %in% col2get2[c(1,2, #temperature of upper sonde and its QC status
                                                                    7,8,# SC of upper sonde and its QC status
                                                                    13,14,# fdom of upper sonde and its QC status
                                                                    15,16,# chl of upper sonde and its QC status
                                                                    19,20,# turb of upper sonde and its QC status
                                                                    9,10,# pH and its QC status
                                                                    5,6) # gage height and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_Liberty)[3:18] <- c("do","do_flag","tempC","tempC_flag","gage","gage_flag","sc","sc_flag", "pH","pH_flag","fdom","fdom_flag","chl","chl_flag","turb","turb_flag")

save(df_Liberty, file = here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Liberty.RData"))
```

For 2022 data from USGS Grizzly Bay station near Tule Red
```{r}
library(tidyverse)
library(dataRetrieval)
rm(list = ls())

siteNumber <- "380631122032201"
parameterCd <- "00065" # Discharge
startDate <- "2022-01-01T00:00"
endDate <- "2022-12-31T23:45"
timezone <- "America/Los_Angeles"

parameterQ <- read.csv(here::here("raw","ExtPrograms","USGS","USGS_parameters.csv"))

dailyDataAvailable <- whatNWISdata(
 siteNumber = siteNumber,
 service = "iv"
)
dailyDataAvailable$parameter <- NA
dailyDataAvailable2 <- merge(dailyDataAvailable, parameterQ[,c(1,3)], by = "parm_cd")
siteINFO <- readNWISsite(siteNumber)
siteAll <- readNWISdata(sites = siteNumber, service = "iv", startDate = startDate, endDate = endDate,tz = timezone)

#save(siteAll, file = here::here("working", "USGS_11455485.RData"))

#load(here::here("working", "USGS_11455485.RData"))

col2get <- data.frame(colnames(siteAll),NA)
col2get[,2] <- stringr::str_match(col2get[,1], "_\\d+")
col2get$parm_cd <- substr(col2get[,2],2,nchar(col2get[,2]))
colnames(col2get) <- c("colsNames","num1","parm_cd")
col2get2 <- merge(col2get,parameterQ[,c(1,3)],by = "parm_cd")

df_Grizzly <- siteAll[,c(2,3,8,9, # 8 and 9 are DO and its QC status
                         which(colnames(siteAll) %in% col2get2[c(1,2, #temperature of upper sonde and its QC status
                                                                    3,4,# SC of upper sonde and its QC status
                                                                    9,10,# fdom of upper sonde and its QC status
                                                                    11,12,# chl of upper sonde and its QC status
                                                                    13,14,# turb of upper sonde and its QC status
                                                                    5,6)# pH and its QC status
                                                                  ,"colsNames"] 
                                  ))] 

colnames(df_Grizzly)[3:16] <- c("do","do_flag","tempC","tempC_flag","sc","sc_flag", "pH","pH_flag","fdom","fdom_flag","chl","chl_flag","turb","turb_flag")

save(df_Grizzly, file = here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Grizzly.RData"))
```

Check the coverage of Accepted vs Provisional data
```{r}
library(ggplot2)
library(ggpubr)
rm(list = ls())

load(here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_ToeDrain.RData"))
load(here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Liberty.RData"))
load(here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Toland.RData"))
load(here::here("working", "ExtPrograms", "ExtProg_2023", "USGS_Grizzly.RData"))

list_all <- list(df_ToeDrain, df_Liberty, df_Toland, df_Grizzly)
names(list_all) <- c("Toe Drain","Liberty Island","Toland Landing", "Grizzly Bay")

dat2subset <- c("dateTime","do","tempC","sc","pH","fdom","chl","turb")
flag2subset <- c("dateTime","do_flag","tempC_flag","sc_flag","pH_flag","fdom_flag","chl_flag","turb_flag")

list_long <- list()
list_plo <- list()
for(i in 1:length(list_all)){
        df_longData <- reshape2::melt(list_all[[i]][,colnames(list_all[[i]]) %in% dat2subset], id.vars = c("dateTime"))
        df_longQC <- reshape2::melt(list_all[[i]][,colnames(list_all[[i]]) %in% flag2subset], id.vars = c("dateTime"))
        
        df_long <- cbind.data.frame(df_longData, df_longQC[,3])
        colnames(df_long)[4] <- "flag"
        ploX <- ggplot(df_long[which(df_long$flag %in% c("A","P")),], aes(x = dateTime, y = value)) +
                geom_point(aes(color = flag)) +
                facet_grid(variable ~., scales = "free") +
                ggtitle(names(list_all)[[i]])
        list_long[[i]] <- df_long
        list_plo[[i]] <- ploX
}
names(list_plo) <- names(list_all)
names(list_long) <- names(list_all)
multi_plo <- ggarrange(list_plo[[1]], list_plo[[2]], list_plo[[3]], list_plo[[4]],
                         ncol = 4, nrow = 1,
                         common.legend = FALSE, legend = "bottom")
ggsave(paste("ExtPrograms_All",".png",sep = ""), multi_plo, width = 1920, height = 1080, dpi = 150, units = "px")

save(list_all,list_long, file = here::here("working","ExtPrograms", "ExtProg_2023","AllExtProgram.RData"))
```

